In [1]:
import numpy as np
import sys

<h1> The Basics </h1>

Numpy are faster that list. 
because they uses less bytes of memory.
also no type checking when iterating through objects.
Numpy uses contiguous Memory.
Effective Cache Utilization.
Application of Numpy?
    MATLAB Replacement(mathematics)
    plotting
    backend of Pandas
    machine learning.

In [2]:
a = np.array([1,2,3], dtype = "int16") # initializing array and defining the type
a

array([1, 2, 3], dtype=int16)

In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])#2d arary
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [4]:
a.ndim#getting the dimension

1

In [5]:
a.shape #getting the shape
b.shape

(2, 3)

In [6]:
#get the type of an array
a.dtype
b.dtype

dtype('float64')

In [7]:
#getting the size
a.itemsize

a.size #give the total number of element.
a.nbytes

6

<h2> Accessing/Changin specific elements, rows, columns etc</h2>

In [8]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a


array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [9]:
#getting specific element [r,c]
a[1, 5]

13

In [10]:
#getting a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [11]:
#getting a specific column
a[:, 2]

array([ 3, 10])

In [12]:
#Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2] # or a[0, 1:-1:2]

array([2, 4, 6])

In [13]:
a[1,5] = 20 #changing elements
a
a[:,2] = [1,2]
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

In [14]:
##3d Examples.

In [15]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [16]:
#getting specific element (work inside out)
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [17]:
#replacing
b[:,1,:] = [[8,3],[3,2]]

<h2>Initializing Different Types of Arrays</h2>

In [18]:
#All 0s Matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
#All 1s Matrix
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
#Any other number
np.full((2,3),23, dtype="float16")

array([[23., 23., 23.],
       [23., 23., 23.]], dtype=float16)

In [21]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [22]:
#random decimal number
np.random.rand(4,2,3) 
#np.random.random_sample(a.shape)

array([[[0.85604184, 0.9996368 , 0.54382114],
        [0.80338585, 0.62553882, 0.95260895]],

       [[0.3412479 , 0.85861649, 0.40189368],
        [0.18108296, 0.44933703, 0.36989763]],

       [[0.13361951, 0.64887791, 0.07452478],
        [0.13563693, 0.1101626 , 0.46466038]],

       [[0.3695655 , 0.30987309, 0.98282878],
        [0.63219785, 0.49360321, 0.22341077]]])

In [23]:
#Random Integers values
np.random.randint(4,7,size=(3,3))

array([[4, 4, 6],
       [5, 5, 6],
       [4, 6, 4]])

In [24]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [26]:
#Excercise
arr = np.ones((5,5))
arr[1:4,1:4] = [0]
arr[2,2] = 9
arr


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

##Be careful when copying arrays!!!

In [37]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
a
b

array([100,   2,   3])

<strong> Mathematics</strong>

In [50]:
a = np.array([1,2,3,4])
a


array([1, 2, 3, 4])

In [42]:
a + 2, a * 2, a / 2

(array([3, 4, 5, 6]), array([2, 4, 6, 8]), array([0.5, 1. , 1.5, 2. ]))

In [51]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [52]:
a ** 2

array([ 1,  4,  9, 16])

In [54]:
np.sin(a), np.cos(a)

(array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ]),
 array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362]))

##### Linear Algebra

In [60]:
a = np.ones((2,3))
a

b = np.full((3,2), 2)
b

np.matmul(a,b) #matrix multiplication.

array([[6., 6.],
       [6., 6.]])

In [64]:
c = np.identity(3)
np.linalg.det(c) #determinate of a matrix.
#You can also get determinant, singular vector decompostition, eigenvalues, Matrix None, Inverse.

1.0

<h3> Statistics</h3>

In [89]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
np.min(stats)

1

In [91]:
np.max(stats, axis = 1)

array([3, 6])

In [92]:
np.sum(stats, axis = 0)

array([5, 7, 9])

<h2>Reorganizing Arrays </h2>

In [95]:
before = np.array([[1,2,3,4],[5,6,7,8]])
before.shape



(2, 4)

In [104]:
after = before.reshape((2,2,2))
after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

<h2> Vertically Stacking vectors </h2>

In [108]:
#vertical Stack
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2])
np.vstack([v1,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [111]:
#horizontal Stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

<h2> Miscellaneous </h2>

In [12]:
file_data = np.genfromtxt("Data.txt", delimiter = ",")
file_data = file_data.astype("int32") #converting the data to an int.
file_data

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

<h2> Boolean Masking and Advanced Indexing </h2>

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

In [16]:
#file_data > 50
file_data[file_data > 50]``````````````````

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [18]:
#You can index with a list in Numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [20]:
np.any(file_data > 50, axis = 0)# Telling when any values are greater than 50 for each column(axis = 0).

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [21]:
np.all(file_data > 50, axis = 0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [28]:
((file_data > 50) & (file_data < 100))
(~((file_data > 50) & (file_data < 100))) #not equall to the condition.

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])